name: movisual_edge

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.10.4
  camera: ^0.10.5
  http: ^1.2.0
  uuid: ^4.3.3
  image: ^4.1.7

flutter:
  uses-material-design: true
  assets:
    - assets
    - assets/gender_model.tflite 
